# 数据同步模块配置
sync:
  # 同步任务配置
  scheduler:
    # 是否启用定时同步
    enabled: true
    # 检查间隔（毫秒）
    check-interval: 60000
  
  # 告警配置
  alert:
    # 邮件配置
    mail:
      # 发件人
      from: noreply@company.com
      # 邮件主题
      subject: "[OA系统] 数据同步失败告警"
      # 邮件模板路径
      template: templates/mail/sync-alert.html
    
    # 钉钉配置
    dingtalk:
      # 消息标题
      title: "OA系统数据同步失败告警"
      # 消息模板路径
      template: templates/dingtalk/sync-alert.json

# 数据源配置
datasource:
  # AD域数据源配置
  ad:
    url: ldap://ad.company.com:389
    base-dn: dc=company,dc=com
    username: cn=admin,dc=company,dc=com
    password: ${AD_PASSWORD:password}
    
  # ERP系统数据源配置
  erp:
    url: http://erp.company.com/api/sync
    username: erp_sync
    password: ${ERP_PASSWORD:password}
    
  # HR系统数据源配置
  hr:
    url: https://hr.company.com/api/v2/sync
    api-key: ${HR_API_KEY:api_key}
    
  # CRM系统数据源配置
  crm:
    url: http://crm.company.com/sync
    username: crm_sync
    password: ${CRM_PASSWORD:password}

# 日志配置
logging:
  level:
    com.oahelp.service.impl.SyncServiceImpl: DEBUG
    com.oahelp.scheduler.SyncScheduler: INFO